version: "3"

services:
  mysql-server:
    container_name: mysql-server
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: mypassword
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
